version: '3.8'

services:
  backend:
    build: 
      context: ./smartie
      
    container_name: smartie_backend
    ports:
      - "8000:8000"
    volumes:
      - ./smartie:/app
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    build: ./client
    container_name: smartie_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
    command: ["npm", "start"]

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
